version: "1.0"

services:
  app:
    build: .
    ports:
      - 3000:3000
    networks:
        - mongodb-net
    environment: 
      MONGO_URI: 'mongodb://mongodb:27017/myappdb'
      restart: always

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - mongodb-net
    ports:
      - 27071:27071

volumes:
  mongodata:

networks:
    mongodb-net: